version: '3.8'

services:
    app:
        build: .
        image: fuzzy-lamp:${VERSION}
        env_file:
            - .env
        volumes:
            - .:/usr/src/app
        ports:
            - "5000:5000"
